### ISSUE TITLE
Problems about Running the Scripts

### ISSUE THREAD

**Issue by vanusy** [mveres01/multi-contact-grasping#5]
My system is ubuntu 16.04 and V-REP  version is 3.5 EDU. First, I open "grasp_scene.ttt". But when I run the simulation, I see the barretthand disappeared. Then I run the script "collect_grasps.py", but it comes out that an error occurs. Here is the traceback:
Traceback (most recent call last):

  File "<ipython-input-1-1bede7c1d027>", line 1, in <module>
    runfile('/media/xiaoqing/Project/Git Grasp/multi-contact-grasping/src/collect_grasps.py', wdir='/media/xiaoqing/Project/Git Grasp/multi-contact-grasping/src')

  File "/home/xiaoqing/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/xiaoqing/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/media/xiaoqing/Project/Git Grasp/multi-contact-grasping/src/collect_grasps.py", line 274, in <module>
    collect_grasps(mesh_path, sim)

  File "/media/xiaoqing/Project/Git Grasp/multi-contact-grasping/src/collect_grasps.py", line 165, in collect_grasps
    gripper_offset=candidate_offset)

  File "/media/xiaoqing/Project/Git Grasp/multi-contact-grasping/src/collect_grasps.py", line 107, in generate_candidates
    h=(p - triangles)**2

ValueError: operands could not be broadcast together with shapes (95,3) (12,3) 

**Could you help me about this problem? Many thanks.**

**Comment by mveres01** [comment]
It looks like this came from a newer version of Trimesh; The command for installing the library should have been: ``pip install trimesh==2.20.21``

I've just pushed to the dev branch for the newest Trimesh (``pip install trimesh==2.29.10``) . Can you do a ``git checkout dev`` and see if that works? 

Incidentally, this also helped track down a bug with generating candidates.

**Comment by vanusy** [comment]
Thanks a lot. I update Trimesh version to 2.29.10. However the same problems exit.
When I run the simulation, I see the barretthand disappeared. 
I run the script "collect_grasps.py", error  still comes out.
Does that related to the V_REP version? since I use the newest  V-REP 3.5 EDU.

**Comment by mveres01** [comment]
The hand disappearing is normal - it'll come back once it tries grasping. I think 3.5 should be OK, but we'll find out once the script gets running. 

The changes aren't on the main branch yet - can you try pulling from dev? You can either clone /download the branch directly https://github.com/mveres01/multi-contact-grasping/tree/dev or do a git checkout from the command line:

```
cd multi-contact-grasping
git checkout dev
```

You should see the following change:

(__old__) points = trimesh.sample.sample_surface_even(mesh, num_samples)
(__new__) points, face_idx = trimesh.sample.sample_surface_even(mesh, num_samples)

**Comment by vanusy** [comment]
Many thanks! According to your suggestion, I try it and finds It works out. Here is what I do to solve this problem:
Open the shell commend, and input: 
git clone https://github.com/mveres01/multi-contact-grasping
cd multi-contact-grasping
git checkout dev

Then I run the script src/collect_grasps.py. it works out correctly.

Thanks a lot. I will do grasp research based on it and make some progression in the future.

**Comment by mveres01** [comment]
Great :) Glad it worked out.
